### PR TITLE
[WIP] Refactoring #17

### PR DESCRIPTION
**Pull request by PiotrCzapla**
You can run this as follows:

`python -m ulmfit.pretrain_lm --dir-path 'data/wiki/wikitext-2'  --qrnn=True train_lm --num_epochs=1`

### CODE REVIEW

**Comment by PiotrCzapla** [comment]
@dust0x @sebastianruder  have a look if we can go in that direction. This lets us run the experiments directly from command line using fire, and also load them in notebooks.
The only issue I've noticed so far is that fire gives a lot of options when you run, as it lists all the fields as a possible command to execute after init
`python -m ulmfit.pretrain_lm --dir-path 'data/wiki/wikitext-2' ` 

There is no support for loading the experiments yet, and we still use the same parameters as previously ie subword=True instead of tokenizer='subword'.

**Comment by sebastianruder** [comment]
Sure, this makes a lot of sense! Thanks for this, @PiotrCzapla. Sorry that I've been so unresponsive in the past week. Just have a lot going on with writing up the thesis.

**Comment by dust0x** [comment]
This will definitely be useful! One thing to note (in reference to the directory structure you proposed in the issue) is that the vocabulary and the sentencepiece model does not change for any two given experiments on the same dataset. So spm.model, spm.vocab and itos.pkl need not be separately placed into folders for the same dataset..

**Comment by PiotrCzapla** [comment]
They may change if you change the vocabulary size, or you add preprocessing (like lowercasing). So it is rather important to keep them next to the models and in separated folders. Right now if you change the preprocessing rules you will break the model a bit I think.

**Comment by dust0x** [comment]
Hi Piotr, I've written a self attention module for the classifier, and seeing that there are a lot of major changes in the refactor branch, I used it as the basis. Is there a way to create a new PR with my changes that branches from this one?

**Comment by dust0x** [comment]
Also, please note that `test_bilm_classifier_loads_encoder()` isn't working, possible because of [this](https://github.com/fastai/fastai/commit/8288e32ef4275473d190c7b9963837c3da6a287a#diff-b0aeca655fbaa828f07d13e96f40b683) commit in fastai.

A partial error trace:

```
~/Documents/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in __getitem__(self, idxs)
     92     def __getitem__(self,idxs:int)->Any:
     93         idxs = try_int(idxs)
---> 94         if isinstance(idxs, numbers.Integral): return self.get(idxs)
     95         else: return self.new(self.items[idxs], xtra=index_row(self.xtra, idxs))
     96 

~/Documents/anaconda3/lib/python3.6/site-packages/fastai/data_block.py in get(self, i)
    346         o = self.items[i]
    347         if o is None: return None
--> 348         if self.one_hot: return self.reconstruct(o.astype(np.float32))
    349         return MultiCategory(one_hot(o, self.c), [self.classes[p] for p in o], o)
    350 

ValueError: could not convert string to float: 'fast ai is a cool project'
```

**Comment by PiotrCzapla** [comment]
I'll have a look. @dust0x  you can simply make a branch out of the refactor branch and add your changes there.

**Comment by PiotrCzapla** [comment]
Guys,  I've updated to newest fastai (the version that changes batch shape), fixed BiLM, fixed sentencepice so it gives good results on IMDB (94.6%), and clean up a bit. 

I think I would like to merge it to master, so that we can recommend this branch to be used by others trying to train ULMFiT.

Let me know what you think.

**Comment by PiotrCzapla** [comment]
I've created ulmfit_multilingual_refactor branch in n-waves/fastai with the version of fastai on which I've tested the code.

**Comment by PiotrCzapla** [comment]
@sebastianruder, they are working. I'm not sure if xnli is working as I haven't yet tested it.
One change is that we use Fastai tokens `xxbos`, `xxunk` etc as they are left unchanged by MosesTokenizer, while the standard xml like tokens like `<unk>` are replaced to `<`, `unk`, `>` and there is no workaround for that.

**Pull request merged**
