### PR TITLE
General data processing for classification and data reading for XNLI

### PR DESCRIPTION
**Pull request by sebastianruder**
I've added a utility method for reading different datasets that should be easily extensible to new ones for other language. I've added a method for reading the XNLI data. The nice thing is that we don't need to tokenize it as it's already tokenized with Moses.

In the main classification method, the datasets are built from the ids. I find a bit weird that `TextClasDataBunch.from_ids` accepts `tst_ids` as an argument, but not `tst_lbls`. 

At the moment, the premise and hypothesis are just concatenated with a special `<sep>` token as discussed here: https://github.com/n-waves/ulmfit-multilingual/issues/5. Other options are possible.

I've only tested that the data processing works and haven't run the full training yet.

### CODE REVIEW

**Comment by NirantK** [comment]
Hey @sebastianruder I am trying the imdb classifier with `qrnn=False` with following: 

```python-traceback
$ python ulmfit/train_clas.py data/
Dataset: imdb. Language: en.
Reading the data...
Reading data/imdb/train.csv...
Reading data/imdb/test.csv...
Train size: 22500. Valid size: 2500. Test size: 25000.
Traceback (most recent call last):
  File "ulmfit/train_clas.py", line 143, in <module>
    fire.Fire(new_train_clas)
  File "/home/nirant/anaconda3/envs/ulmfit/lib/python3.6/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/nirant/anaconda3/envs/ulmfit/lib/python3.6/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/nirant/anaconda3/envs/ulmfit/lib/python3.6/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "ulmfit/train_clas.py", line 100, in new_train_clas
    val_ids=ids[VAL], bs=bs, bptt=bptt)
TypeError: from_ids() missing 2 required positional arguments: 'train_ids' and 'valid_ids'
```

Did you try this by any chance? There is a similar issue with our master branch as well. 
Is it possible that we are working off slightly different versions of fastaiv1?

**Comment by sebastianruder** [comment]
Thanks for the pointer! I had been working with an old fastai v1 version. :-/ I've just updated the method.
I'm getting an error in `TextClasDataBunch.from_ids` now, though, which is related to the validation labels:
`AttributeError: 'CategoryList' object has no attribute 'classes'`
Have you seen this before?

**Comment by NirantK** [comment]
I saw it on our master when I tried it with the fastaiv1 version I have. Either way, I have merged your XNLI changes - all but most recent commit. 

I have tested [this classifier-fixes branch](https://github.com/n-waves/ulmfit-multilingual/tree/classifier-fixes) for 
- imdb with LSTM 
- added a utils for going from `aclImdb.tgz` to `train.csv` and `test.csv` 
- added few small tweaks so that I can train on a smaller GPU with 8G RAM

**Comment by PiotrCzapla** [comment]
The fastai changed a bit since this code was written by Sebastain, I'm working on a fix now to train the classifier.

**Comment by NirantK** [comment]
Hmm @PiotrCzapla - I think I must've made the bulk of the changes you are about to because I am able to run the code end to end. 

It'd be super nice of both you and @sebastianruder to *test* that [branch](https://github.com/n-waves/ulmfit-multilingual/tree/classifier-fixes) with XNLI and IMDB (QRNN) - because I don't have the compute for so many tests.

**Comment by PiotrCzapla** [comment]
Superb ! thank you. Let me test it end to end.

**Comment by sebastianruder** [comment]
These changes have already been merged in https://github.com/n-waves/ulmfit-multilingual/pull/9, so I'm closing this PR.

**Comment by PiotrCzapla** [comment]
It seems that github does not let you create multiple pull request for single branch, and now it is complaining that the PR was closed by there are unmerged commits
screenshot 2018-11-18 at 19 29 20

**Comment by sebastianruder** [comment]
Hmm, the only unmerged commit should be my last one (https://github.com/n-waves/ulmfit-multilingual/pull/7/commits/c9c827c4202ae1ead0881ccb07250a20c9437589). I think these changes have already been made in another commit anyway.

**Pull request closed without merging**
